# Generated by Django 4.0.3 on 2022-05-26 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_resimgalerimodel_urun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategororimodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.kategororimodel'),
        ),
    ]
