# Generated by Django 4.0.3 on 2022-05-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_kategororimodel_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resimgalerimodel',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
