# Generated by Django 4.0.3 on 2022-05-30 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_resimgalerimodel_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategororimodel',
            name='parent',
        ),
        migrations.AddField(
            model_name='kategororimodel',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.kategororimodel'),
        ),
    ]
